  </div>
<div id="rightside">
  <p><img src="http://os_extranet_images.s3.amazonaws.com/285164_original.png" width="220" /></p>
  <p><i>From our free weekly practica!</i></p>
<hr>
<h2><strong>Monthly Workshops</strong></h2>
<p>On the last weekend of every month, we feature Saturday and Sunday workshops led by visiting world-class tango instructors and host our special Milonga Luz de Luna with guest DJs<br>
<a href="https://s3.amazonaws.com/os_extranet_files_test/27282_98823_Workshop_schedule_2018.pdf">View the full schedule for 2018</a>
</p>
<h2><strong>Lessons</strong></h2>
  <h3>
    Beginner Series:</h3>
  <p>
    Next beginner lesson 4-week series level I with Juan Brache begins February 5, 2018 at Just Because Center, 1013 W State St, Ithaca, from 5:30-6:45pm.</p>
 <h3>
    Intermediate Series:</h3>
  <p>
    For students who already have a grasp of the basic fundamentals, Juan Brache teaches occasional Intermediate series covering specific topics in more depth. These take place at Just Because Center, 1013 W State St, Ithaca, from 8-9:15pm. <a href="mailto:tango-l-request@cornell.edu?body=leave">Join our list serve</a> to hear about the next series that is offered.</p>
  <h3>
    Drop-in intro lessons:</h3>
<p>Curious about tango, but not sure you want to commit to a series yet? Come to our <b>Thursday practices</b>! Take a free intro class, 7-8pm, then stay to practice what you've learned. <a href="/org/tango/Calendar">See calendar</a> for times and locations and <a href="mailto:tango-l-request@cornell.edu?body=leave">sign up to our listserv</a> to receive updates.</p>


</div>

  </div></div><div style="clear: both;"></div>
<div id="footer">
  <div id="footer_container">
       <p style="font-size:20px; text-align:right">See you on the dance floor!</p>


  </div>
</div>

</body>
</html>
