<body>
  <div id="header">
    <div id="org_title">

<!-- this is where you change the organization name at the top of every page. Please leave it within the h1 tags to maintain styling. If you would like to upload a logo it can also go in here by using html -->

      <h1>Ithaca Tangueros </h1>
    </div>
  </div>
  <div id="content_wrapper">

<!-- this is the vertical navigation in the left sidebar for your site. to add a link simply re-create one of the lines that begins with <li> and ends with </li>, inside will be a link using the quick url format for OrgSync Links. More information can be found in the website builder help -->

    <div id="navigation">
      <ul>
        <li><a href="[[page:home]]">Home</a></li>
                                        <li><a href="[[page:About]]">About</a></li>
          <li><a href="[[page:Calendar]]">Calendar</a></li>
          <li><a href="[[page:Events]]">Events</a></li>
          <li><a href="[[page:Pictures]]">Pictures</a></li>
          <li><a href="[[page:ContactUs]]">Contact Us</a></li>
                  </ul>

      <h2><strong>Before you take another step...</strong></h2>
  <h3><strong><a href="mailto:tango-l-request@cornell.edu?body=join">Join our mailing list!</a><strong></h3>

<p>The Ithaca Tangueros list serve is the best source for all announcements of tango events in Ithaca, including last-minute time and location changes.<br>
To join, send an email to <br><strong><a href="mailto:tango-l-request@cornell.edu?body=join">tango-l-request@cornell.edu</a></strong> with the word &quot;<strong><em>join</em></strong>&quot; in the body.<br><br>

To no longer receive emails, <a href="mailto:tango-l-request@cornell.edu?body=leave">send a message to the same address</a> with the word &quot;<strong><em>leave</em></strong>&quot; in the body.<br>
More instructions <a href="http://www.it.cornell.edu/services/elist/howto/user/leave.cfm">here</a>.</p>

<h3><strong><a href="http://www.facebook.com/groups/IthacaTango/">Join us on Facebook!</a></strong></h3>
<p>Tango is a social dance and Facebook is <strong>the</strong> social network of choice for tango dancers everywhere. <br><a href="http://www.facebook.com/groups/IthacaTango/">Follow us on Facebook</a> to see more detailed event descriptions, let others know your dancing plans, and make new tango friends.</p>
    </div>
    <div id="content"><div id="leftside">
